// todo-solid/src/components/NoteList.jsx
import { For } from "solid-js"
import SingleNote from "./SingleNote"
import { useNotesContext } from "../context/NotesContext";

export default function NoteList(){
    const {notes} = useNotesContext()

    return(
        <div className="note_list">
            <For each={notes()}>{(note) => 
                <SingleNote key={note.id} note={note}/>
            }
            </For>
        </div>
    )
}

// todo-react/src/components/NoteList.jsx
import SingleNote from "./SingleNote"

export default function NoteList({notes}) {

    return (
        <div className="note_list">
            {!notes && <p>No notes so far</p>}
            {notes && notes.map(note => {
                return (
                    <SingleNote key={note.id} note={note}/>
                )
            })}
        </div>
    )
}
