// todo-vue/src/components/NoteList.vue
<template>
    <div class="note_list">
        <template v-for="note in notelist" :key="note.id">
            <SingleNote :note="note"></SingleNote>
        </template>
    </div>
</template>

<script>
import { inject } from 'vue';
import SingleNote from './SingleNote.vue';

export default {
    name: 'NoteList',
    components: { SingleNote },
    setup() {
        const notelist = inject('notes')
        return {notelist}
    }
}
</script>

// todo-react/src/components/NoteList.jsx
import SingleNote from "./SingleNote"

export default function NoteList({notes}) {

    return (
        <div className="note_list">
            {!notes && <p>No notes so far</p>}
            {notes && notes.map(note => {
                return (
                    <SingleNote key={note.id} note={note}/>
                )
            })}
        </div>
    )
}
