// todo-vue-ts/src/components/NoteList.vue
<template>
    <div class="note_list">
        <template v-for="note in notelist" :key="note.id">
            <SingleNote :note="note"></SingleNote>
        </template>
    </div>
</template>

<script setup lang="ts">
import { inject } from 'vue';
import { Note } from '../interfaces';
import SingleNote from './SingleNote.vue';

const notelist = inject<Note[]>('notes') as Note[]

</script>

// todo-react/src/components/NoteList.jsx
import SingleNote from "./SingleNote"

export default function NoteList({notes}) {

    return (
        <div className="note_list">
            {!notes && <p>No notes so far</p>}
            {notes && notes.map(note => {
                return (
                    <SingleNote key={note.id} note={note}/>
                )
            })}
        </div>
    )
}
