// todo-react/src/components/SingleNote.jsx
import axios from "axios"
import { useContext, useState } from "react"
import { NotesContext } from "../App"

export default function SingleNote({note}) {
    const {setNotes} = useContext(NotesContext)
    const [isEditing, setEditing] = useState(false)

    const handleUpdate = async (noteToUpdate) => {
        try{
            await axios.patch(
                'http://localhost:4000/notes/' + note.id, {title: noteToUpdate.title, done: noteToUpdate.done}
            )
            setNotes(currentNotes => {
                return currentNotes.map(n => n.id === noteToUpdate.id ? noteToUpdate : n)
            })
        }catch(error){
            console.error('Failed to mark note: ' + error)
        }
    }

    const handleDelete = async () => {
        try{
            await axios.delete('http://localhost:4000/notes/' + note.id)
            setNotes(currentNotes => {
                return currentNotes.filter(n => n.id !== note.id)
            })
        }catch (error){
            console.error('Failed to delete note: ' + error)
        }
    }

    let content

    if (isEditing) {
        content = (
            <>
                <input type="text" value={note.title}
                    onChange={e => handleUpdate({...note, title: e.target.value})} />
                <button onClick={() => {setEditing(false)}}>Save</button>
            </>
        )
    } else {
        content = (
            <>
                <span>{note.title}</span>
                {note.done === false && <button onClick={() => setEditing(true)}>Edit</button>}
                {note.done === true && <button disabled onClick={() => setEditing(true)}>Edit</button>}
            </>
        )
    }

    return (
        <div key={note.id} className="single_note">
            <input type="checkbox" checked={note.done} 
                onChange={e => handleUpdate({...note, done: e.target.checked})} />
            {content}
            <button onClick={() => handleDelete(note.id)}>Delete</button>
        </div>
    )
}

// todo-solid/src/components/SingleNote.jsx
import axios from "axios";
import { Show, createSignal } from "solid-js";
import { useNotesContext } from "../context/NotesContext";

export default function SingleNote(props) {
    const {notes, setNotes} = useNotesContext()
    const [isEditing, setEditing] = createSignal(false)

    const handleUpdate = async (noteToUpdate) => {
        try {
            const response = await axios.patch(
                'http://localhost:4000/notes/' + props.note.id, { title: noteToUpdate.title, done: noteToUpdate.done }
            )
            setNotes(notes().map(n => n.id === response.data.id ? response.data : n))
        } catch (error) {
            console.error('Failed to change note: ' + error)
        }
    }

    const handleDelete = async () => {
        try {
            const response = await axios.delete('http://localhost:4000/notes/' + props.note.id)
            setNotes(notes().filter(n => n.id !== props.note.id))
        } catch (error) {
            console.error('Failed to delete note: ' + error)
        }
    }

    return (
        <div key={props.note.id} className="single_note">
            <input type="checkbox" checked={props.note.done}
                onChange={e => handleUpdate({ ...props.note, done: e.target.checked })} />
            <Show when={isEditing()} fallback={
                <>
                    <span>{props.note.title}</span>
                    <Show when={props.note.done} fallback={
                        <button onClick={() => setEditing(true)}>Edit</button>
                    }>
                        <button disabled>Edit</button>
                    </Show>
                </>
            }>
                <input type="text" value={props.note.title}
                    onChange={e => handleUpdate({ ...props.note, title: e.target.value })}
                    onKeyDown={e => { if (e.key === "Enter") setEditing(false) }} />
                <button onClick={() => setEditing(false)}>Save</button>
            </Show>
            <button onClick={handleDelete}>Delete</button>
        </div>
    )

}
