// todo-react-ts/src/components/NoteList.tsx
import React from 'react'
import { Note } from '../interfaces'
import { SingleNote } from './SingleNote'

type NoteListProps = {
    noteList: Note[] | null
}

export const NoteList: React.FC<NoteListProps> = ({ noteList }) => {
    return (
        <div className="note_list">
            {!noteList && <p>No notes so far</p>}
            {noteList && noteList.map(note => {
                return (
                    <SingleNote key={note.id} note={note} />
                )
            })}
        </div>
    )
}

// todo-vue-ts/src/components/NoteList.vue
<template>
    <div class="note_list">
        <template v-for="note in notelist" :key="note.id">
            <SingleNote :note="note"></SingleNote>
        </template>
    </div>
</template>

<script setup lang="ts">
import { inject } from 'vue';
import { Note } from '../interfaces';
import SingleNote from './SingleNote.vue';

const notelist = inject<Note[]>('notes') as Note[]

</script>
