// todo-svelte-ts/src/components/NoteForm.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { DB_LINK, type Note } from "../interfaces";
    import { NotesStore } from "../store/NotesStore";
    import axios from "axios";

    let newNote: string = ""
    let notes = [] as Note[]
    onMount(() => NotesStore.subscribe((data) => {notes = data}))

    const addNote = async () => {
        if(newNote === ""){
            alert("Can't add empty notes")
            return
        }
        const response = await axios.post(DB_LINK, {
            title: newNote, done: false
        })
        NotesStore.set([...notes, response.data])
        newNote = ""
    }
</script>

<div class="add_note_block">
    <input type="text" bind:value={newNote}>
    <button on:click={() => addNote()}>Add</button>
</div>

// todo-vue-ts/src/components/NoteForm.vue
<template>
    <div class="add_note_block">
        <input type="text" v-model="newNote" @keydown.enter="addNote">
        <button @click="addNote">Add</button>
    </div>
</template>

<script setup lang="ts">
import axios from 'axios'
import { inject, ref } from 'vue';
import { DB_LINK, Note } from '../interfaces';

let newNote = ref<string>("")
const notelist = inject<Note[]>('notes') as Note[]
const addNote = async () => {
    if(newNote.value === ""){
        alert("Can't add empty note")
        return
    }
    const response = await axios.post(DB_LINK, {
        title: newNote.value, done: false
    })
    notelist?.value.push(response.data)
    newNote.value = ""
}
</script>
